import Head from 'next/head';
import styles from '~/styles/Home.module.css';

import { decrement, increment, incrementByAmount } from '~/store/counter';
import { login, logout, User, loginAsync } from '~/store/auth';
import { useAppDispatch, useAppSelector, RootState } from '~/store/store';

type Counter = {
  value: number;
};

type State = {
  counter: Counter;
  auth: {
    user: User;
  };
};

export default function Home() {
  const count = useAppSelector((state: RootState) => state.counter.value);
  const user = useAppSelector((state: RootState) => state.auth.user);

  const dispatch = useAppDispatch();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <p>{user && user.name}</p>
            <h1>logout</h1>
            <button onClick={() => dispatch(login({ name: 'john', phone: 123241 }))}>login</button>
            <button onClick={() => dispatch(logout())}>logout</button>
            <button aria-label='Decrement value' onClick={() => dispatch(loginAsync(3))}>
              loginAsync
            </button>
          </div>
          <div>
            <h1>redux</h1>
            <div>
              <button aria-label='Increment value' onClick={() => dispatch(increment())}>
                Increment
              </button>
              <span>{count}</span>
              <button aria-label='Decrement value' onClick={() => dispatch(decrement())}>
                Decrement
              </button>
              <button aria-label='Decrement value' onClick={() => dispatch(incrementByAmount(234))}>
                incrementByAmount
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
