import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { gql } from 'graphql-request';
import { useGQLQuery } from './useGQLQuery';
import Link from 'next/link';

const GQL_EXAMPLE = gql`
  query {
    program(id: 76) {
      cooperate
    }
  }
`;

export default function Home() {
  const { data, isLoading, isError } = useGQLQuery(['index'], GQL_EXAMPLE, null, {
    refetchOnWindowFocus: false,
    staleTime: 60 * 60 * 1000
  });

  if (isLoading || isError) {
    return <div>Loading</div>;
  }

  // console.log(data.program.cooperate);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <button>
          <Link href='/audiobook'>audiobook</Link>
        </button>
        <div>program</div>
        <div>{data.program.cooperate}</div>
      </main>
    </div>
  );
}
